services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_HOST= "%"
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mydb
    ports:
      - 3306:3306